name: Testing the 'my-outputs-action' custom Composite action
run-name: ${{ github.actor }} is testing to see how outputs from a custom action work! 🧪

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository # need to checkout the repo otherwise we do not know where the action's code is
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Use my composite action
        id: my-action
        # this is the relative path to where our action lives in this repo
        uses: ./.github/actions/my-outputs-action

      - name: Display the output result of the composite action
        # Access the output script-result using the steps.<step-id>.outputs.<output-name> syntax.
        run: |
          echo "Script Result: ${{ steps.my-action.outputs.script-result }}"
