name: Test the custom Composite action
run-name: ${{ github.actor }} is taking the custom Composite action out for a spin! 🏎️

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository # need to checkout the repo otherwise we do not know where the action's code is
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Use my composite action
        # this is the relative path to where our action lives in this repo
        uses: ./.github/actions/my-composite-action
        # if our composite action is shared from another repository, we reference it like this:
        # uses: owner/repository/.github/actions/my-composite-action@v1
        with:
          node-version: "18"
